### ISSUE TITLE
i got an error

### ISSUE THREAD

**Issue by lpwwpl** [tcalmant/demo-ipopo-qt#1]
i got an error:
framework_uid = reference.get_property(pelix.remote.PROP_FRAMEWORK_UID)
AttributeError: module 'pelix.remote' has no attribute 'PROP_FRAMEWORK_UID'

how to clear the error

**Comment by tcalmant** [comment]
The property constant has been renamed `pelix.remote.PROP_ENDPOINT_FRAMEWORK_UUID` in order to match its OSGi counterpart.
